# Generated by Django 3.2 on 2024-02-28 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_online', models.BooleanField(default=False)),
                ('opponent_online', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Game Created. Waiting for opponent'), (2, 'Game Started'), (3, 'Game Ended')], default=1)),
                ('c_player', models.CharField(default=1, max_length=3)),
                ('owner_cards', models.CharField(blank=True, max_length=2000)),
                ('opponent_cards', models.CharField(blank=True, max_length=2000)),
                ('Cards_deck_play', models.CharField(blank=True, max_length=2000)),
                ('Last_played', models.CharField(blank=True, max_length=2000)),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
